FROM ruby:2.5

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

ENV INSTALL_PATH /app
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN bundle install

COPY . .
#COPY config/secrets.docker.sample.yml config/secrets.yml
#COPY config/database.docker.sample.yml config/database.yml

EXPOSE 3000

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]